version: 0.0
os: linux
files:
  - source: /webserver/hello_world.py
    destination: /home/ubuntu/app/
  - source: /webserver/templates
    destination: /home/ubuntu/app/templates
permissions:
    - object: scripts/start_server.sh
      owner: root
      mode: 777
      type:
        - file
    - object: scripts/stop_server.sh
      owner: root
      mode: 777
      type:
        - file
hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
