version: 0.0
os: linux
files:
  - source: /webserver/hello_world.py
    destination: /home/ubuntu/app/
  - source: /webserver/templates
    destination: /home/ubuntu/app/templates
hooks:
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
